[package]
name = "uuid-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { workspace = true, features = ["serde"] }
uuid-simd = { workspace = true }
serde = { workspace = true }
_workspace-hack = { version = "0.1", path = "../_workspace-hack" }
